services:
  web:
    container_name: studiu_next
    build: .
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NEXTAUTH_SECRET=$NEXTAUTH_SECRET
      - DATABASE_URI=$DATABASE_URI
    volumes:
      - uploads:/app/storage

volumes:
  uploads:
