services:
  app:
    container_name: stud-iu
    build:
      context: .
    image: nextjs-prod
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      prisma-migrator:
        condition: service_completed_successfully
    environment:
      NODE_ENV: production
      DATABASE_URI: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public"
    networks:
      - localnet
    volumes:
      - ./uploads_data:/app/storage

networks:
  localnet:
    driver: bridge

volumes:
  postgres_data:
