name: Test stud_iu_front
on: [push, workflow_dispatch, pull_request]

jobs:
  install-cache:
    name: Install & Cache
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Cache node modules
        uses: actions/cache@v4
        id: cache-node-modules
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-v1

  lint-check:
    name: Run Linters
    runs-on: ubuntu-latest
    needs: [ 'install-cache' ]
    steps:
      - name: Get the repository code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Restore node modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-v1

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run Lint
        run: npm run lint

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: ['lint-check']
    steps:
      - name: Get the repository code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Restore node modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-v1

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run build
        run: npm run build

  telegram-notify:
    name: Telegram Notification
    runs-on: ubuntu-latest
    needs: [build]
    environment: production
    if: always()
    steps:
      - name: Send Telegram notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            <b>${{ needs.build.result == 'success' && '✅ Build Success' || '❌ Build Failed' }}</b>
            
            <b>📦 Repo:</b> <a href="https://github.com/${{ github.repository }}">${{ github.repository }}</a>
            <b>🌿 Branch:</b> ${{ github.ref_name }}
            <b>👤 User:</b> ${{ github.actor }}
            
            <b>💬 Commit:</b>
            <code>${{ github.event.head_commit.message }}</code>
            
            🔗 <a href="https://github.com/${{ github.repository }}/commit/${{ github.sha }}">View Changes</a>
            🎬 <a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">View Action</a>

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    environment: production
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        env:
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          DATABASE_URI: ${{ secrets.DATABASE_URI }}
        with:
          host: ${{ vars.SSH_HOST }}
          port: ${{ vars.SSH_PORT }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          envs: NEXTAUTH_SECRET, DATABASE_URI, UPLOADS
          script: |
            cd ${{ vars.PROJECT_DIR }}
            git stash
            git checkout dev
            git pull origin dev
            docker compose down --remove-orphans
            docker compose -f docker-compose.ci.yaml up --build -d
